# Generated by Django 3.2.7 on 2022-12-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrutamientoVehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='problem',
        ),
        migrations.AlterField(
            model_name='publication',
            name='autor',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='solutions_method',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
